# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 02:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(default='static/images/headimg_default.jpg', null=True, upload_to=''),
        ),
    ]
