# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-10-23 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20181023_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(default='/static/images/headimg_default.jpg', null=True, upload_to=''),
        ),
    ]
